http:
  # Add the router
  routers:
    web-service:
      entryPoints:
        - websecure
      service: web-service
      rule: "Host(`webservice.earias.me`)"
      tls:
        certResolver: lets-encr      

  # Add the service
  services:
    web-service:
      loadBalancer:
        servers:
          - url: "https://google.com"
        loadbalancer.server.scheme: http
        passHostHeader: false